version: "3"
services:
  spring-boot-elk-app:
    restart: always
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    networks:
      - error-log
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
    networks:
      - error-log

networks:
  error-log:

